version: "3"
services:
    # MySQL Service
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
        env_file: .env
        ports:
            - 5000:27017
        volumes:
            - mongodb_data_container:/data/db

    # Express API APP
    api:
        container_name: express_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        restart: always
        environment:
            PORT: 3000
            DB: mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/express_mongo_ts?authSource=admin
        depends_on:
            - mongodb
        volumes:
            - ./src/:/app/src/

volumes:
    mongodb_data_container: {}
